server:
  port: 8080
spring:
  application:
    security:
      jwt:
        secret-key: 6bedd1cc1529ae30a2b2a70eec4d321ddd78ab72cad1870fd8bddb763707e441
        expiration: 86400000
        refresh-token:
          expiration: 604800000
