server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FabLab?createDatabaseIfNotExist=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    security:
      jwt:
        secret-key: 6bedd1cc1529ae30a2b2a70eec4d321ddd78ab72cad1870fd8bddb763707e441
        expiration: 86400000
        refresh-token:
          expiration: 604800000
