server:
  port: 8080
spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/FabLab?
  #    username: postgres
  #    password: "0000"
  #    driver-class-name: org.postgresql.Driver
  #  jpa:
  #    database: postgresql
  #    hibernate:
  #      ddl-auto: create-drop
  #    show-sql: false
  #    properties:
  #      hibernate:
  #        format_sql: true
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    security:
      jwt:
        secret-key: 6bedd1cc1529ae30a2b2a70eec4d321ddd78ab72cad1870fd8bddb763707e441
        expiration: 86400000
        refresh-token:
          expiration: 604800000
