server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FabLab
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    security:
      jwt:
        secret-key: 885D7594D81B366FB67AEF56F61AA
        expiration: 86400000
        refresh-token:
          expiration: 604800000
